<?
$hierarchy = umiHierarchy::getInstance();
foreach ($variables['void:lines'] as $list) {
	$page = $hierarchy->getElement($list['attribute:id']);
	$str = $list['node:name'];
	$count_max = 96;
	$result_str = ""; // в эту переменную запишем результат
	// если строка, больше предела + 3(3 точки в конце)
	if (mb_strlen($str, 'utf-8') > ($count_max + 3)) {
		// обрезаем строку
		$sub_str = mb_substr($str, 0, $count_max, 'utf-8');
		// удаляем пробелы в начале и конце обрезанной строки, и дописываем в конец три точки
		$result_str = trim($sub_str) . "...";
		// добавляем к тексту атрибут title, для вывода подсказки при наведении
		$result_str = "$result_str";
	} else {
		// если строка и так короткая
		$result_str = $str;
	}
	echo '
	<a class="tape__item" href="' . $list['attribute:link'] . '">
		<div class="tape__date">'.$page->getValue('publish_time')->getFormattedDate('d').'<br>'.$this->translate($page->getValue('publish_time')->getFormattedDate('m')).'</div>
		<div class="tape__anons">'.$result_str.'</div>
	</a>
	';
}
$limit = 3; //ссылок в навигации на каждую сторону
$per_page = $variables['per_page']; // элементов на странице
$total = $variables['total'];
echo $this->render(array(
	"total" => $total,
	"per_page" => $per_page,
	"limit" => $limit,
	"numpages" => $this->macros("system", "numpages", array($total, $per_page, null, null, $limit))
), "partials/pagination/pagination");
