<?php

$hierarchy = umiHierarchy::getInstance();
foreach ($variables['void:lines'] as $compilation) :
	$obPage = $hierarchy->getElement($compilation['attribute:id']);
	$cropText = $obPage->getValue('anons');
		
	echo '
	<div class="compilation__item">
		<div class="compilation__title">'.$compilation['node:name'].'</div>
		<div class="compilation__subtitle">'.$obPage->getValue('spc_subtitle').'</div>
		<div class="compilation__preview">'.$obPage->getValue('spc_preview').'</div>
		<div class="compilation__box">
			<div class="compilation__box-item compilation__date">'.$this->translate('published').': <span>'.$obPage->getValue('publish_time')->getFormattedDate('d.m.Y').'</span></div>
			<div class="compilation__box-item compilation__isbn">'.$obPage->getValue('spc_isbn').'</div>
			<a href="'.$obPage->getValue('spc_link_download').'" target="_blank" class="compilation__box-item compilation__download">Скачать сборник</a>
		</div>
	</div>
	';
endforeach;

$limit = 3; //	ссылок в навигации на каждую сторону
$per_page = $variables['per_page']; // элементов на странице
$total = $variables['total'];
echo $this->render(array(
	"total" => $total,
	"per_page" => $per_page,
	"limit" => $limit,
	"numpages" => $this->macros("system", "numpages", array($total, $per_page, null, null, $limit))), "library/numpages"
);
?>