<?
// var_dump($variables);
$count = count($variables['void:lines']);
echo '<div class="search-result-count">По вашему запросу найдено страниц: <span>'.$count.'</span></div>';
echo '<div class="search-result">';
foreach ($variables['void:lines'] as $key => $search_item) :
	$trim_text = substr($search_item['node:context'], 0, 480);
	$trim_text = rtrim($trim_text, "!,.;:-");
	$trim_text = substr($trim_text, 0, strrpos($trim_text, ' '));

	echo '
		<div class="search-result__item">
			<a href="'.$search_item['attribute:link'].'" class="search-result__name">
				'.$search_item['attribute:name'].'
			</a>
			<div class="search-result__text">
				'.$trim_text."… ".'
			</div>
		</div>';
endforeach;
echo '</div>';

$limit = 3; //	ссылок в навигации на каждую сторону
$per_page = $variables['per_page']; // элементов на странице
$total = $variables['total'];
echo $this->render(array(
	"total" => $total,
	"per_page" => $per_page,
	"limit" => $limit,
	"numpages" => $this->macros("system", "numpages", array($total, $per_page, null, null, $limit))), "library/numpages");
?>