<?
$hierarchy = umiHierarchy::getInstance();
foreach ($variables['void:lines'] as $news) {
	$page = $hierarchy->getElement($news['@id']);
	echo '
		<div class="guide">
			<div class="guide__img"><img src="'.$page->getValue('image').'" alt="'.($page->getValue('image') ? $page->getValue('image')->getAlt() : '').'" />
				<div class="guide__name">'.$page->getValue('name').'</div>
			</div>
			<div class="guide__content">
				<a href="'.$news['@link'].'" class="guide__title">'.$page->getValue('post').'</a>
				<div class="guide__text">
				 '.$page->getValue('academic_degree').'
				</div>
				<div class="guide__contacts">';
				if ($page->getValue('phone')) {
					echo '<div class="guide__phone"><a href="tel:'.$page->getValue('phone').'">'.$page->getValue('phone').'</a></div>
					';
				}
				if ($page->getValue('address')) {
					echo '<div class="guide__address">'.$page->getValue('address').'</div>
					';
				}
				if ($page->getValue('email')) {
					echo '<div class="guide__email"><a href="mailto:'.$page->getValue('email').'">'.$page->getValue('email').'</a></div>
					';
				}
				if ($page->getValue('blog')) {
					echo '<div class="guide__link"><a href="/rectors-blog/" target="_blank">'.$page->getValue('blog').'</a></div>
					';
				}
	echo '</div>
			</div>
		</div>';
}
