<?
$hierarchy = umiHierarchy::getInstance();
foreach ($variables['void:lines'] as $content) {
	$value = $hierarchy->getElement($content['@id']);

	echo '
	
	<div class="slider-dep__content-sync__item">
		<div class="row">
			<div class="col-lg-12">
				<div class="dep-tabs">
					<div class="dep-tabs__item active dep-tabs__programs">
						<img src="/templates/ksu/img/dep/ati/online.svg" alt="" class="dep-tabs__img">
					</div>
					<div class="dep-tabs__item dep-tabs__science">
						<img src="/templates/ksu/img/dep/ati/artificial-intelligence.svg" alt="" class="dep-tabs__img">
					</div>
					<div class="dep-tabs__item dep-tabs__content">
						<img src="/templates/ksu/img/dep/ati/lab.svg" alt="" class="dep-tabs__img">
					</div>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-lg-12">
				<div class="dep-tabs__body">
					<div class="programs dep-tabs__block active">
						<h3 class="programs__title">
							'.$value->getValue('title_special').'
						</h3>
						<div class="row">
							<div class="col-lg-4">
								<div class="programs__preview">
									<img src="'.$value->getValue('icon').'" alt="">
								</div>
							</div>
							<div class="col-lg-8">
								<div class="programs__preview-text">
									'.$value->getValue('preview').'
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-lg-12">
								<div class="programs__content">
									'.$value->getValue('content').'
								</div>
							</div>
						</div>
					</div>

					<div class="science dep-tabs__block">
						'.$value->getValue('science').'
					</div>
					<div class="lab dep-tabs__block">
						'.$value->getValue('lab').'
					</div>
				</div>
			</div>
		</div>
	</div>

	';
}
?>
