<?
// print_r('<pre>');
// print_r($variables['items']['nodes:item']);
// print_r('</pre>');
$hierarchy = umiHierarchy::getInstance();


$counter=1;
foreach ($variables['items']['nodes:item'] as $value) {
	$page = $hierarchy->getElement($value['@id']);
	$email = ($page->getValue('email_pps')) ? : $page->getValue('email_pps');
	if($variables['id']==1398 || $variables['id']==1402 || $variables['id']==1482)
		echo '<div class="temp-pps__box-inner">
			<div class="temp-pps__info">
			<a href="'.$value['@link'].'"><div class="temp-pps__text temp-pps__name">'.$page->getValue('h1').'</div></a>
			</div>
		</div>';
	else
	echo '
		<div class="temp-pps__box-inner">
			<div class="temp-pps__images" style="background: url('.$page->getValue('photo_pps').') center / cover no-repeat;"></div>
			<div class="temp-pps__info">
				<div class="temp-pps__text temp-pps__name">'.$page->getValue('h1').'</div>
				<div class="temp-pps__text temp-pps__place">
					'.$page->getValue('place_pps').'
				</div>
				<div class="temp-pps__text temp-pps__email">
					<a href="mailto:'.$page->getValue('email_pps').'">'.$page->getValue('email_pps').'</a>
				</div>
				<div class="temp-pps-content">
					<div class="temp-pps-title" id='.$counter.'>
						О преподавателе
					</div>
					<div class="temp-pps-title__box-'.$counter.'" style="display: none;">
					'.$page->getValue('content').'
					</div>
				</div>
			</div>
		</div>';
		$counter++;
}
?>