<?
//print_r($variables);
$objectsCollection = umiObjectsCollection::getInstance();
foreach ($variables['nodes:banners'] as $banner)
{
	$object=$objectsCollection->getObject($banner['attribute:id']);
	//print_r($object->getValue('class'));
	/*	print_r('<a href='.$object->getValue('url').'><span class="icon"><i class="'.$object->getValue('class').'"></i></span></a>');*/
	print_r('<a href="'.$object->getValue('url').'" class="header__social__link"><img src="/templates/ksu/img/icons/social/'.$object->getValue('file-name').'" alt="'.$object->getValue('file-name').'"></a>');
}
print_r('<a href="https://www.facebook.com/baitursynov.university" class="header__social__link"><img src="/templates/ksu/img/icons/social/facebook.svg" alt="facebook"></a>');
print_r('<a href="https://telegram.me/ksu_edu" class="header__social__link"><img src="/templates/ksu/img/icons/social/telegram.svg" alt="telegram"></a>');

print_r('<a data-fancybox data-src="#callModal" href="javascript:;" class="call-center"><span>Call-центр</span></a>');
?>