	<!-- Поиск -->
	<div class="search-box">
		<div class="container">
			<form action="/search_result" method="GET" class="search-form">
				<input type="text" name="search" placeholder="<?= $this->translate('enter') ?>..." class="search-form__input">
			</form>
		</div>
	</div>

	<!-- Popup call-center -->
	<a href="tel:87142931010" class="popup-call show">
		Call center - 8 (7142) 93-10-10
	</a>

	<div style="display: none;" id="liveModal" class="">
		<iframe width="560" height="315" src="https://www.youtube.com/embed/JEsl1v0TJJU" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
	</div>

	<!-- Модальное окно - Call-Center -->
	<div style="display: none;" id="callModal" class="call-modal">
		<div class="call-modal__logo"><img src="/templates/ksu/img/logo.png" alt="KSU"></div>
		<div class="call-modal__bg-top"><img src="/templates/ksu/img/window/bg-top.png" alt="elem1"></div>
		<ul class="call-modal__list">
			<li><?= $this->translate('call_931010') ?> <a href="tel:87142931010">8(7142)93-10-10</a></li>
			<li><?= $this->translate('call_511120') ?> <a href="tel:87142511120">8(7142)51-11-20</a><br /><a href="tel:87776379785">8(777)637-97-85</a></li>
			<li><?= $this->translate('call_390190') ?> <a href="tel:87142390190">8(7142)39-01-90</a></li>
			<li><?= $this->translate('call_511100') ?> <a href="tel:87142511100">8(7142)51-11-00</a></li>
			<li><?= $this->translate('call_390630') ?> <a href="tel:87142390630">8(7142)39-06-30</a></li>
			<li><?= $this->translate('call_760674') ?> <a href="tel:87772760674">8(777)276-06-74</a></li>
			<li><?= $this->translate('call_530162') ?>: <a href="tel:87142530162">8(7142)53-01-62</a><br><a href="87142990544">8(7142)99-05-44</a></li>
		</ul>
		<div class="call-modal__bg-bottom"><img src="/templates/ksu/img/window/bg-bottom.png" alt="elem2"></div>
	</div>

	<!-- Модальное окно - видео инжинирингового центра -->
	<div style="display: none;" id="engineerModal" class="video-engineer">
		<iframe width="100%" height="100%" src="https://www.youtube.com/embed/UtHOiPz8qrM" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
	</div>

	<footer class="footer">
		<img src="/templates/ksu/img/footer-ksu.png" alt="KSU" class="footer__img">
		<div class="footer__text"><?= $this->translate('footer_copyright'); ?></div>
		<div style="position: absolute; bottom: 28px; left: 3rem;">
			<a href="https://www.liveinternet.ru/click" target="_blank"><img src="https://counter.yadro.ru/logo?27.11" title="LiveInternet: показано количество просмотров и посетителей" alt="" style="border:0" width="88" height="120" /></a>
		</div>
	</footer>

	<script src="https://yastatic.net/share2/share.js" defer></script>
	<script src="/templates/ksu/js/app.min.js?<? echo $js_version ?>"></script>
	<!-- <script src="/templates/ksu/js/new-y.js?<? echo $js_version ?>"></script> -->


	<? if (@$variables["full:page"]->getAltName() == "enrollee-form") : ?>
		<script src="/templates/ksu/js/selectize.min.js"></script>
		<script src="/templates/ksu/js/enrollee.js"></script>
		<link rel="stylesheet" href="/templates/ksu/css/enrollee.css">
	<? endif; ?>

	<!-- Метрики -->
	<!-- Google Analytics -->
	<script src="https://www.googletagmanager.com/gtag/js?id=UA-158283481-1" async></script>
	<script>
		window.dataLayer = window.dataLayer || [];

		function gtag() {
			dataLayer.push(arguments);
		}
		gtag('js', new Date());
		gtag('config', 'UA-158283481-1');
	</script>
	<!-- Yandex.Metrika -->
	<script type="text/javascript">
		(function(m, e, t, r, i, k, a) {
			m[i] = m[i] || function() {
				(m[i].a = m[i].a || []).push(arguments)
			};
			m[i].l = 1 * new Date();
			k = e.createElement(t), a = e.getElementsByTagName(t)[0], k.async = 1, k.src = r, a.parentNode.insertBefore(k, a)
		})
		(window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");
		ym(57175126, "init", {
			clickmap: true,
			trackLinks: true,
			accurateTrackBounce: true,
			webvisor: true
		});
	</script>
	<script src="//code-ya.jivosite.com/widget/i0csGcI0ba" async></script>
	</body>

	</html>