<?
function trim_news($str, $znaki = 100) {
	$str = strip_tags(trim($str));
	if (mb_strlen($str, 'utf-8') <= $znaki) {
		return $str;
	}
	$arrStr1 = explode(' ', $str);
	$arrStr2 = explode(' ', mb_substr($str, 0, $znaki));
	$str = '';
	foreach ($arrStr2 as $key => $val) {
		if ($val == $arrStr1[$key]) {
				$str .= $val . ' ';
		}
	}
	return trim($str) . '...';
}

$hierarchy = umiHierarchy::getInstance();
foreach ($variables['void:lines'] as $news) {
	$page = $hierarchy->getElement($news['attribute:id']);
	$cropText = $page->getValue('anons');
		
	echo '
	<div class="page-news-list__item">
		<div class="page-news-list__text">
			<a href="'.$news['attribute:link'].'" class="page-news-list__title">'.$news['node:name'].'</a>
			<div class="page-news-list__subtitle">
				'.trim_news($cropText, 125).'
			</div>
			<div class="page-news-list__info">
				<div class="page-news-list__date">'.$page->getValue('publish_time')->getFormattedDate('d.m.Y').'</div>
				<div class="page-news-list__times"></div>
			</div>
		</div>
	</div>';
}

$limit = 3; //	ссылок в навигации на каждую сторону
$per_page = $variables['per_page']; // элементов на странице
$total = $variables['total'];
echo $this->render(array(
	"total" => $total,
	"per_page" => $per_page,
	"limit" => $limit,
	"numpages" => $this->macros("system", "numpages", array($total, $per_page, null, null, $limit))), "partials/pagination/pagination");