<?
// print_r('<pre style="display: none;">');
// print_r($variables['items']['nodes:item']);
// print_r('</pre>');

foreach ($variables['items']['nodes:item'] as $item) :

	$nav__item = ($item['items']) ? print_r('<li class="nav__item">') : print_r('<li class="nav__item nav__item--bg">');
	if(!($item['items'])) print_r('<a href="'.$item['@link'].'">');
	print_r('<div class="nav__item__title">'.$item['@name'].'</div>');
	if ($item['items']) {
		print_r('<ul class="dropdown">');
		foreach ($item['items']['nodes:item'] as $underitem) :
			$target = in_array($underitem['@id'], [45, 83, 109, 4305, 4306, 4307]) ? '_blank' : '_self';
			// if ($underitem['@has-children'] == 1) {
			// 	$hasChildren = 'dropdown__item--three';
			// }
			echo 
			'<li class="dropdown__item">
				<a class="dropdown__item_link " target="'.$target.'" href="'.$underitem['@link'].'">
					'.$underitem['@name'].'
				</a>';
echo '</li>';
		endforeach;
		print_r('</ul>');
	}
	if(!($item['items'])) print_r('</a>');
	print_r('</li>');	
endforeach;
?>