<?
print('<ul id="accordion" class="accordion">');
foreach ($variables['items']['nodes:item'] as $item)
{
	print_r('<li class="mobile_item">');

	if(!($item['items'])) {
		print_r('<a href="'.$item['@link'].'">');
		print_r('<div class="link link-bg">'.$item['@name'].'</div>');
		print_r('</a>');
	} else {
		print_r('<div class="link link-bg">'.$item['@name'].'<img src="/templates/ksu/img/icons/arrow-down-sign-to-navigate.png" alt="down"></div>');
	
		print_r('<ul class="submenu">');
		foreach ($item['items']['nodes:item'] as $underitem)
		{
			print_r('<li class="dropdown__item"><a class="dropdown__item_link" href="'.$underitem['@link'].'">'.$underitem['@name'].'</a></li>');
		}
		print_r('</ul>');
	}

	print_r('</li>');
}
	print_r('<li class="mobile_item">');
		echo '<a href="http://school.ksu.edu.kz/" class="nav__item__title link link-bg" style="text-align:left;" target="_blank">Талапкер 2020</a>';
	print_r('</li>');

print('</ul>');
?>