<?
// print_r('<pre>');
// print_r($variables['void:lines']);
// print_r('</pre>');
function rus_date() {
	// Перевод
	 $translate = array(
	 "am" => "дп",
	 "pm" => "пп",
	 "AM" => "ДП",
	 "PM" => "ПП",
	 "Monday" => "Понедельник",
	 "Mon" => "Пн",
	 "Tuesday" => "Вторник",
	 "Tue" => "Вт",
	 "Wednesday" => "Среда",
	 "Wed" => "Ср",
	 "Thursday" => "Четверг",
	 "Thu" => "Чт",
	 "Friday" => "Пятница",
	 "Fri" => "Пт",
	 "Saturday" => "Суббота",
	 "Sat" => "Сб",
	 "Sunday" => "Воскресенье",
	 "Sun" => "Вс",
	 "January" => "Января",
	 "Jan" => "Янв",
	 "February" => "Февраля",
	 "Feb" => "Фев",
	 "March" => "Марта",
	 "Mar" => "Мар",
	 "April" => "Апреля",
	 "Apr" => "Апр",
	 "May" => "Мая",
	 "May" => "Мая",
	 "June" => "Июня",
	 "Jun" => "Июн",
	 "July" => "Июля",
	 "Jul" => "Июл",
	 "August" => "Августа",
	 "Aug" => "Авг",
	 "September" => "Сентября",
	 "Sep" => "Сен",
	 "October" => "Октября",
	 "Oct" => "Окт",
	 "November" => "Ноября",
	 "Nov" => "Ноя",
	 "December" => "Декабря",
	 "Dec" => "Дек",
	 "st" => "ое",
	 "nd" => "ое",
	 "rd" => "е",
	 "th" => "ое"
	 );
	 // если передали дату, то переводим ее
	 if (func_num_args() > 1) {
	 $timestamp = func_get_arg(1);
	 return strtr(date(func_get_arg(0), $timestamp), $translate);
	 } else {
	// иначе текущую дату
	 return strtr(date(func_get_arg(0)), $translate);
	 }
	 }
$hierarchy = umiHierarchy::getInstance();
foreach ($variables['void:lines'] as $list) {
	$page = $hierarchy->getElement($list['attribute:id']);
	$monthEl = $page->getValue('publish_time')->getFormattedDate('m');
	$dayEl = $page->getValue('publish_time')->getFormattedDate('d');
	$monthElRuss = '';
	if ($monthEl == '01'){
		$monthElRuss = "Янв";
	}

	echo '
	<div class="news-feed__item">
	<div class="news-feed__date">'.$dayEl.'<br>'.$monthElRuss.'</div>
	<a href="'.$list['attribute:link'].'">
		<div class="news-feed__text">'.$list['node:name'].'</div>
	</a>
	</div>
	';
}
