<?
//print_r($variables);

$hierarchy = umiHierarchy::getInstance(); 
//print_r("<div class=\"header-news__ticker\">");
//print_r("<ul id=\"webTicker\">");
$i=0;
foreach ($variables['void:lines'] as $news)
{
	$page = $hierarchy->getElement($news['attribute:id']);
		//print_r($page->getValue('anons_pic')->getFilePath());
	//$data = $this->macros('system', 'makeThumbnail', array($page->getValue('anons_pic')->getFilePath(), 800 , auto));  ОШИПКА
	print_r('
		<li><a href="'.$news['attribute:link'].'">'.$page->getValue('publish_time')->getFormattedDate('d.m.Y').' - '.$news['node:name'].'</a></li>
	');
	$i++; if($i>=3) break;
}
//print_r("</div>");
//print_r("</div>");
?>
