<?
// print_r('<pre>');
// print_r($variables);
// print_r('</pre>');
$hierarchy = umiHierarchy::getInstance();
print_r("<div class=\"news\">");
foreach ($variables['void:lines'] as $news) {
	$page = $hierarchy->getElement($news['attribute:id']);
	print_r('<a href="'.$news['attribute:link'].'" class="news_item">
							<div class="news_text">
								'.$news['node:name'].'
							</div>
							<div class="news_date">
								'.$page->getValue('publish_time')->getFormattedDate('d.m.Y').'
							</div>
							<img src="'.$page->getValue('anons_pic').'" alt="Anons">
						</a>');
}
print_r("</div>");


$limit = 3; //	ссылок в навигации на каждую сторону
$per_page = $variables['per_page']; // элементов на странице
$total = $variables['total'];
//echo $total;
// echo $this->render(array(
// 		"total" => $total,
// 		"per_page" => $per_page,
// 		"limit" => $limit,
// 		"numpages" => $this->macros("system", "numpages", array($total, $per_page, null, null, $limit))), "library/numpages");
?>