<?
//print_r($variables);
$nameOfType = $variables[1];
print_r('<div class="list">');
$name = 'item';
$hierarchy = umiHierarchy::getInstance();
$i = 0;
foreach ($variables[0]['void:lines'] as $news) {
	if ($i >= 3) break;
	$page = $hierarchy->getElement($news['attribute:id']);

	if ($page->getValue($nameOfType) == 1) {
		print_r('<div class="' . $name . '">
										<div class="' . $name . '-img"><img src="' . $page->getValue('anons_pic') . '" alt="" class="img-responsive" style="width:230px;"></div>
										<div class="item-info">
											<a href="' . $news['attribute:link'] . '">' . $news['node:name'] . '</a>
										</div>
									</div>');
		$name = $name . 'm';
		$i++;
	}
}
print_r("</div>");
