<? include "lang/langselect.phtml"; ?>
<? include "include/head.phtml"; ?>
<? $_REQUEST['lang'] = $variables['@lang']; ?>

<header class="header">
	<div class="container">
		<? include 'top-header.phtml' ?>
	
		<div class="content">
			<style>
				.content__title div.main-title {
					font-size: 30px;
					margin: 0 12px;
					text-shadow: 2px 2px 2px #333;
				}

				@media (max-width: 992px) {
					.content__title div.main-title {
						font-size: 22px;
					}

					.carousel-text {
						font-size: 22px;
					}

					.content__title br {
						display: block;
					}
				}
			</style>
			<div class="owl-carousel content__title">
				<!-- <div class="carousel-text">
					<span class="mart">8</span><br>
					<span><?= $this->translate('mart'); ?></span><br>
					<?= $this->translate('8_mart'); ?>
				</div> -->
				<!-- <div class="carousel-text"><span>Наурыз мейрамы құтты болсын!</span></div> -->
				<div class="main-title"><?= $this->translate('cru_named_baitursinova'); ?></div>
			</div>
			<?
			switch ($variables['@domain']) {
				case 'ksu.edu.kz':
					echo '
					<div class="header-news">
						<div class="header-news__ticker">
							<ul id="webTicker">
							'. $this->render($this->macros('news', 'lastlist', array('newslist/all-news, newslist/for-the-entrant, newslist/education, newslist/science, newslist/university-life, newslist/ruhani-zhagyru', null, null, true)), 'news/lastlist').'
							</ul>
						</div>
						'.$this->render($this->macros('news', 'lastlist', array('newslist/all-news, newslist/for-the-entrant, newslist/education, newslist/science, newslist/university-life, newslist/ruhani-zhagyru', null, null, true)), 'news/rightoplist').'
					</div>';
					break;
				default:
					echo '';
					break;
			}
			?>
		</div>
	</div>
</header>

<section id="menu">
	<div class="container">
		<div class="row">
			<div class="col-lg-3 col-md-3 col-sm-6 col-6">
				<div class="stud-nav stud-nav_student">
					<a class="stud-nav__link" href="/<?= urlencode($variables['@lang']); ?>/4block/distance_learning/">
						<div class="stud-nav__title"><?= $dot ?></div>
					</a>
				</div>
			</div>

			<div class="col-lg-3 col-md-3 col-sm-6 col-6">
				<div class="stud-nav stud-nav_abb">
					<a class="stud-nav__link" href="/<?= urlencode($variables['@lang']); ?>/enrollee/">
						<div class="stud-nav__title"><?= $abitur ?></div>
					</a>
				</div>
			</div>
			<div class="col-lg-3 col-md-3 col-sm-6 col-6">
				<div class="stud-nav stud-nav_voen">
					<a class="stud-nav__link" href="/<?= urlencode($variables['@lang']); ?>/4block/voennaya-kafedra/">
						<div class="stud-nav__title"><?= $voennaya ?></div>
					</a>
				</div>
			</div>

			<div class="col-lg-3 col-md-3 col-sm-6 col-6">
				<div class="stud-nav stud-nav_grant">
					<a class="stud-nav__link" href="/<?= urlencode($variables['@lang']); ?>/4block/granty-i-skidki/">
						<div class="stud-nav__title"><?= $grant ?></div>
					</a>
				</div>
			</div>
			<!--div class="col-lg-3 col-md-3 col-sm-6 col-6">
				<div class="stud-nav stud-nav_student">
					<a class="stud-nav__link" href="/<?= urlencode($variables['@lang']); ?>/4block/nashi-vypuskniki/">
						<div class="stud-nav__title"><?= $our ?></div>
					</a>
				</div>
			</div-->
		</div>
		<div class="content-nav">
			<div class="row">
				<div class="col-lg-3 col-md-6 col-sm-6">
					<a href="https://acportal.ksu.edu.kz/ru" target="_blank" class="content-nav__item">
						<?= $anti_portal ?>
						<img src="/templates/ksu/img/icons/header/portal.svg" alt="Портал">
					</a>
				</div>
				<div class="col-lg-3 col-md-6 col-sm-6">
					<a href="/<?= urlencode($variables['@lang']); ?>/timetable/" class="content-nav__item">
						<?= $blocktimetable ?>
						<img src="/templates/ksu/img/icons/header/portal.svg" alt="Портал">
					</a>
				</div>
				<div class="col-lg-3 col-md-6 col-sm-6">
					<a href="/<?= urlencode($variables['@lang']); ?>/block/onlajn-biblioteka" class="content-nav__item">
						<?= $library ?>
						<img src="/templates/ksu/img/icons/header/job.svg" alt="Портал">
					</a>
				</div>
				<div class="col-lg-3 col-md-6 col-sm-6">
					<a href="/<?= urlencode($variables['@lang']); ?>/digital-ecosystem/" target="_blank" class="content-nav__item">
						<?= $this->translate('page_digital_ecosystem') ?>
						<img src="/templates/ksu/img/icons/header/blog.svg" alt="Портал">
					</a>
				</div>
			</div>
			<div class="row">
				<div class="col-lg-3 col-md-6 col-sm-6">
					<a href="http://smart.ksu.edu.kz/" target="_self" class="content-nav__item">
						<?= $this->translate('page_student_service_center') ?>
						<img src="/templates/ksu/img/icons/header/blog.svg" alt="page_student_service_center">
					</a>
				</div>

				<div class="col-lg-3 col-md-6 col-sm-6">
					<a class="content-nav__item" href="/<?= urlencode($variables['@lang']); ?>/covid/">
						Covid-19
						<img src="/templates/ksu/img/icons/header/portal.svg" alt="Портал">
					</a>
				</div>
				<div class="col-lg-3 col-md-6 col-sm-6">
					<a class="content-nav__item" href="http://test.ksu.edu.kz/vacancies">
						Вакансии
						<img src="/templates/ksu/img/icons/header/portal.svg" alt="Портал">
					</a>
				</div>
				<div class="col-lg-3 col-md-6 col-sm-6">
					<a class="content-nav__item" href="/<?= urlencode($variables['@lang']); ?>/educational-activity/trudoustrojstvo-i-professional-naya-praktika/">
						<?= $this->translate('page_career_and_employment_center') ?>
						<img src="/templates/ksu/img/icons/header/portal.svg" alt="Портал">
					</a>
				</div>
			</div>
		</div>
	</div>
</section>

<section id="sec-menu">
	<a data-fancybox data-type="iframe" data-src="/smart3d/smart.html" href="javascript:;">
		<h3 class="sec-menu__title"><?= $regional ?></h3>
		<picture>
			<source srcset='/templates/ksu/img/webp/innovation.webp' type='image/webp'>
			<img src='/templates/ksu/img/innovation.png' alt='SMART-center'>
		</picture>
	</a>
	<a data-fancybox data-src="#engineerModal" href="javascript:;">
		<h3 class="sec-menu__title-left"><?= $engineering ?></h3>
		<picture>
			<source srcset='/templates/ksu/img/webp/sec-mnu1.webp' type='image/webp'>
			<img src='/templates/ksu/img/sec-mnu1.png' alt='Инжиниринговый центр'>
		</picture>
	</a>
	<a data-fancybox data-type="iframe" data-src="/nii3d/biotech.html" href="javascript:;">
		<h3 class="sec-menu__title-right"><?= $biotechnology ?></h3>
		<picture>
			<source srcset='/templates/ksu/img/webp/sec-mnu2.webp' type='image/webp'>
			<img src='/templates/ksu/img/sec-mnu2.png' alt='НИИ прикладной биотехнологии'>
		</picture>
	</a>
</section>

<div class="infographic">
	<div class="container">
		<div class="row">
			<div class="col-lg-3">
				<div class="infographic__item">
					<div class="infographic__number count1">162</div>
					<div class="infographic__text">
						<?= $educational_programs ?>
					</div>
				</div>
			</div>
			<div class="col-lg-3">
				<div class="infographic__item infographic__item--black">
					<div class="infographic__number count2">6532</div>
					<div class="infographic__text">
						<?= $number_students ?>
					</div>
				</div>
			</div>
			<div class="col-lg-3">
				<div class="infographic__item">
					<div class="infographic__number count3">549</div>
					<div class="infographic__text">
						<?= $teaching_staff ?>
					</div>
				</div>
			</div>
			<div class="col-lg-3">
				<div class="infographic__item infographic__item--black">
					<div class="infographic__number count4">223</div>
					<div class="infographic__text">
						<?= $teachers_with_academic ?>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!---------------- Футер ---------------->
<? include 'footer.phtml'; ?>