<? include_once "./templates/ksu/php/partials/header-top.phtml"; ?>

<? $hierarchy = umiHierarchy::getInstance(); ?>

<div class="offer">
	<div class="swiper-container swiper-offer">
		<div class="swiper-wrapper">
			<!-- Slider - start -->
			<?
			$getPageById = $this->macros('content', 'get_page_id', array('/home/banners'));
			$homeSliderChildren = $hierarchy->getChildrenList($getPageById);

			foreach ($homeSliderChildren as $homeSliderChildrenId) :
				$homeSlider = $hierarchy->getElement($homeSliderChildrenId);

				$buttonOneBlank = $homeSlider->home_slider_button_1_blank ? '' : 'target="_blank"';
				$buttonTwoBlank = $homeSlider->home_slider_button_2_blank ? '' : 'target="_blank"';
				$buttonThreeBlank = $homeSlider->home_slider_button_3_blank ? '' : 'target="_blank"';

				$buttonCenterBlock1 = $homeSlider->home_slider_button_1_newp ? 'offer__buttons-center' : '';
				$buttonCenterBlock2 = $homeSlider->home_slider_button_2_newp ? 'offer__buttons-center' : '';
				$buttonCenterBlock3 = $homeSlider->home_slider_button_3_newp ? 'offer__buttons-center' : '';

				$jsCallModal = ($homeSlider->home_slider_button_3_link === 'javascript:;') ? 'data-fancybox data-src="#callModal"' : '';

				$buttonOne = $homeSlider->home_slider_button_1 ? '<a class="' . $buttonCenterBlock1 . '" href="' . $homeSlider->home_slider_button_1_link . '" ' . $buttonOneBlank . '>' . $homeSlider->home_slider_button_1 . '</a>' : '';
				$buttonTwo = $homeSlider->home_slider_button_2 ? '<a class="' . $buttonCenterBlock2 . '" href="' . $homeSlider->home_slider_button_2_link . '" ' . $buttonTwoBlank . '>' . $homeSlider->home_slider_button_2 . '</a>' : '';
				$buttonThree = $homeSlider->home_slider_button_3 ? '<a ' . $jsCallModal . ' class="' . $buttonCenterBlock3 . '" href="' . $homeSlider->home_slider_button_3_link . '" ' . $buttonThreeBlank . '>' . $homeSlider->home_slider_button_3 . '</a>' : '';


				$subtitle = $homeSlider->home_slider_text_under_button ? '<div class="offer__subtitle">' . $homeSlider->home_slider_text_under_button . '</div>' : '';

				echo '
						<div class="swiper-slide">
							<div class="container">
								<div class="offer__box">
									<div class="offer__left">
										<div class="offer__title">' . $homeSlider->content . '</div>
										<div class="offer__buttons">
											' . $buttonOne . '
											' . $buttonTwo . '
											' . $buttonThree . '
										</div>
										' . $subtitle . '
									</div>
									<div class="offer__right">
										<div class="offer__image">
											<div class="offer__gradient-left"></div>
											<div style="background-image: url(' . $homeSlider->getValue('home_slider_image') . '); background-size: cover; height: 400px; width: auto"></div>
											<div class="offer__gradient-right"></div>
										</div>
									</div>
								</div>
							</div>
						</div>
					';
			endforeach;
			?>
			<!-- Slider - end -->
		</div>

		<div class="swiper-button-prev"></div>
		<div class="swiper-button-next"></div>
		<div class="swiper-pagination"></div>
	</div>
</div>

<div class="news">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<div class="news-header">
					<div class="news-header__left">
						<div class="news-header__title"><?= $this->translate('last_news'); ?></div>
					</div>
					<div class="news-header__right">
						<a class="news-header__link" href="/<?= urlencode($variables['@lang']) ?>/newslist/all-news"><?= $this->translate('more_news'); ?></a>
						<a class="news-header__link" href="/<?= urlencode($variables['@lang']) ?>/announcements"><?= $this->translate('announcements'); ?></a>
						<a class="news-header__link" href="/<?= urlencode($variables['@lang']) ?>/conferences"><?= $this->translate('conferences'); ?></a>
					</div>
				</div>
			</div>
		</div>
		<div class="news-list">
			<div class="row">
			<?= $this->render($this->macros('news', 'lastlist', array('newslist/all-news, newslist/for-the-entrant, newslist/education, newslist/science, newslist/university-life, newslist/ruhani-zhagyru', null, null, true)), 'partials/news/news-home-item') ?>
			</div>
		</div>
	</div>
</div>

<section id="menu">
	<div class="container">
		<div class="row">
			<div class="col-lg-3 col-md-3 col-sm-6 col-6">
				<div class="stud-nav" style="background: url(/templates/ksu/img/th-block/univer-life.png) center/cover no-repeat;">
					<a class="stud-nav__link" href="/<?= urlencode($variables['@lang']); ?>/about/univer-life">
						<div class="stud-nav__title">Univer Life</div>
					</a>
				</div>
			</div>

			<div class="col-lg-3 col-md-3 col-sm-6 col-6">
				<div class="stud-nav stud-nav_abb">
					<a class="stud-nav__link" href="/<?= urlencode($variables['@lang']); ?>/enrollee/">
						<div class="stud-nav__title"><?= $this->translate('for-the-entrant') ?></div>
					</a>
				</div>
			</div>
			<div class="col-lg-3 col-md-3 col-sm-6 col-6">
				<div class="stud-nav stud-nav_voen">
					<a class="stud-nav__link" href="/<?= urlencode($variables['@lang']); ?>/4block/voennaya-kafedra/">
						<div class="stud-nav__title"><?= $this->translate('military_department') ?></div>
					</a>
				</div>
			</div>

			<div class="col-lg-3 col-md-3 col-sm-6 col-6">
				<div class="stud-nav stud-nav_grant">
					<a class="stud-nav__link" href="/<?= urlencode($variables['@lang']); ?>/4block/granty-i-skidki/">
						<div class="stud-nav__title"><?= $this->translate('grants_and_discounts') ?></div>
					</a>
				</div>
			</div>
		</div>
		<div class="content-nav">
			<div class="row">
				<div class="col-lg-3 col-md-6 col-sm-6">
					<a href="https://acportal.ksu.edu.kz/<?= urlencode($variables['@lang']); ?>" target="_blank" class="content-nav__item">
						<?= $this->translate('anti_corruption_portal') ?>
						<img src="/templates/ksu/img/icons/header/portal.svg" alt="Портал">
					</a>
				</div>
				<div class="col-lg-3 col-md-6 col-sm-6">
					<a href="/<?= urlencode($variables['@lang']); ?>/timetable/" class="content-nav__item">
						<?= $this->translate('timetable') ?>
						<img src="/templates/ksu/img/icons/header/job.svg" alt="timetable">
					</a>
				</div>
				<div class="col-lg-3 col-md-6 col-sm-6">
					<a href="/<?= urlencode($variables['@lang']); ?>/block/onlajn-biblioteka" class="content-nav__item">
						<?= $this->translate('online_library') ?>
						<img src="/templates/ksu/img/icons/header/job.svg" alt="book">
					</a>
				</div>
				<div class="col-lg-3 col-md-6 col-sm-6">
					<a href="/<?= urlencode($variables['@lang']); ?>/digital-ecosystem/" target="_blank" class="content-nav__item">
						<?= $this->translate('page_digital_ecosystem') ?>
						<img src="/templates/ksu/img/icons/header/blog.svg" alt="Портал">
					</a>
				</div>
			</div>
			<div class="row">
				<div class="col-lg-3 col-md-6 col-sm-6">
					<a href="http://smart.ksu.edu.kz/" target="_self" class="content-nav__item">
						<?= $this->translate('page_student_service_center') ?>
						<img src="/templates/ksu/img/icons/header/blog.svg" alt="page_student_service_center">
					</a>
				</div>
				<div class="col-lg-3 col-md-6 col-sm-6">
					<a class="content-nav__item" href="/<?= urlencode($variables['@lang']); ?>/covid/">
						Covid-19
						<img src="/templates/ksu/img/icons/header/coronavirus.png" alt="covid">
					</a>
				</div>
				<div class="col-lg-3 col-md-6 col-sm-6">
					<a class="content-nav__item" href="http://test.ksu.edu.kz/vacancies">
						Вакансии
						<img src="/templates/ksu/img/icons/header/portal.svg" alt="Портал">
					</a>
				</div>
				<div class="col-lg-3 col-md-6 col-sm-6">
					<a class="content-nav__item" href="/<?= urlencode($variables['@lang']); ?>/educational-activity/trudoustrojstvo-i-professional-naya-praktika/">
						<?= $this->translate('page_career_and_employment_center') ?>
						<img src="/templates/ksu/img/icons/header/portal.svg" alt="Портал">
					</a>
				</div>
			</div>
		</div>
	</div>
</section>

<section id="sec-menu">
	<a data-fancybox data-type="iframe" data-src="/smart3d/smart.html" href="javascript:;">
		<h3 class="sec-menu__title"><?= $this->translate('smart_center') ?></h3>
		<picture>
			<source srcset='/templates/ksu/img/webp/innovation.webp' type='image/webp'>
			<img src='/templates/ksu/img/innovation.png' alt='SMART-center'>
		</picture>
	</a>
	<a data-fancybox data-src="#engineerModal" href="javascript:;">
		<h3 class="sec-menu__title-left"><?= $this->translate('engineering_center') ?></h3>
		<picture>
			<source srcset='/templates/ksu/img/webp/sec-mnu1.webp' type='image/webp'>
			<img src='/templates/ksu/img/sec-mnu1.png' alt='Инжиниринговый центр'>
		</picture>
	</a>
	<a data-fancybox data-type="iframe" data-src="/nii3d/biotech.html" href="javascript:;">
		<h3 class="sec-menu__title-right"><?= $this->translate('research_institute_of_applied_biotechnology') ?></h3>
		<picture>
			<source srcset='/templates/ksu/img/webp/sec-mnu2.webp' type='image/webp'>
			<img src='/templates/ksu/img/sec-mnu2.png' alt='НИИ прикладной биотехнологии'>
		</picture>
	</a>
</section>

<div class="infographic">
	<div class="container">
		<div class="row">
			<div class="col-lg-3">
				<div class="infographic__item">
					<div class="infographic__number count1">162</div>
					<div class="infographic__text">
						<?= $this->translate('implemented_educational_programs') ?>
					</div>
				</div>
			</div>
			<div class="col-lg-3">
				<div class="infographic__item infographic__item--black">
					<div class="infographic__number count2">7192</div>
					<div class="infographic__text">
						<?= $this->translate('contingent_of_students') ?>
					</div>
				</div>
			</div>
			<div class="col-lg-3">
				<div class="infographic__item">
					<div class="infographic__number count3">663</div>
					<div class="infographic__text">
						<?= $this->translate('teaching_staff') ?>
					</div>
				</div>
			</div>
			<div class="col-lg-3">
				<div class="infographic__item infographic__item--black">
					<div class="infographic__number count4">205</div>
					<div class="infographic__text">
						<?= $this->translate('teachers_with_academic_degrees_and_titles') ?>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="container">
	<? include "./templates/ksu/php/partials/yt-slider.phtml"; ?>
</div>

<? include "./templates/ksu/php/partials/footer.phtml"; ?>