<? include "lang/langselect.phtml"; ?>
<? include "include/head.phtml"; ?>	
  <header class="header-inner header">
    <div class="container">
      <? include 'top-header.phtml' ?>
    </div>
  </header>
  <div class="container">
    <div class="breadcrumbs">
      <?= $this->render($this->macros('core', 'navibar'), 'library/navibar') ?>
    </div>
    <div class="graduate">
    <div class="row">
      <?= $this->render($this->macros('content', 'menu', array(null, 3,62)), 'for-blocks/graduate') ?>
    </div>
    </div>
  </div>
<!---------------- Футер ---------------->
<? include 'footer.phtml'; ?>