<?
	include "lang/langselect.phtml";
	include "include/head.phtml";

	$hierarchy = umiHierarchy::getInstance();
	$page = $hierarchy->getElement($variables['@pageId']);
?>
<header class="header-inner header">
	<? include 'top-header.phtml' ?>
</header>
<div class="container">
	<div class="breadcrumbs">
		<?= $this->render($this->macros('core', 'navibar'), 'library/navibar') ?>
	</div>
</div>

<div class="container">
	<div class="row">
		<div class="col-lg-12">
			<div class="tape">
				<h1 class="tape__title">
					<?= $variables['@header'] ?>
				</h1>
				<div class="tape__wrapper">
					<?= $this->render($this->macros('news', 'lastlist', array('granty-stipendii-lgoty-po-oplate', null, 6, false)), 'for-blocks/grants_and_discounts'); ?>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="container">
	<div class="page">
		<div class="page__content-box">
			<!-- <h1 class="page__content-title">
				<?= $variables['@header'] ?>
			</h1> -->
			<div class="page__content">
				<?= $page->content ?>
			</div>
		</div>
	</div>
</div>

<? include 'footer.phtml'; ?>