<? include "lang/langselect.phtml"; ?>
<? include "include/head.phtml"; ?>	
<header class="header header-inner">
	<? include 'top-header.phtml' ?>
</header>
<div class="container">
	<div class="breadcrumbs">
		<?= $this->render($this->macros('core', 'navibar'), 'library/navibar') ?>
	</div>
	<div class="news-list" style="display: block;">
		<?
		switch ($variables['@pageId']) {
			case '72':
				if ($variables['@pageId'] == 72) {
				echo	$this->render($this->macros('content', 'menu', array(null, 3, $variables['@pageId'])), 'macros/guide');
			}	else {
					$hierarchy = umiHierarchy::getInstance();
					$page = $hierarchy->getElement($variables['@pageId']);
				echo '
			<div class="row">
				<div class="guide">
					<div class="guide__img"><img src="'.$page->getValue('image').'" />
						<div class="guide__name">'.$page->getValue('name').'</div>
					</div>
					<div class="guide__content c1">
						<a href="" class="guide__title">'.$page->getValue('post').'</a><br>
						<div class="guide__text">
						'.$page->getValue('academic_degree').'
						</div>
						<div class="guide__contacts">';
						if ($page->getValue('phone')) {
							echo '<div class="guide__phone"><a href="tel:'.$page->getValue('phone').'">'.$page->getValue('phone').'</a></div>
							';
						}
						if ($page->getValue('address')) {
							echo '<div class="guide__address">'.$page->getValue('address').'</div>
							';
						}
						if ($page->getValue('email')) {
							echo '<div class="guide__email"><a href="mailto:'.$page->getValue('email').'">'.$page->getValue('email').'</a></div>
							';
						}
						if ($page->getValue('blog')) {
							echo '<div class="guide__link"><a href="/rectors-blog/" target="_blank">'.$page->getValue('blog').'</a></div>
							';
						}
			echo '</div>
					</div>
				</div>
			</div>';
			}
				break;
			case '31':
				if ($variables['@pageId'] == 31) {
				echo	$this->render($this->macros('content', 'menu', array(null, 3, $variables['@pageId'])), 'macros/guide');
			}	else {
					$hierarchy = umiHierarchy::getInstance();
					$page = $hierarchy->getElement($variables['@pageId']);
				echo '
			<div class="row">
				<div class="guide">
					<div class="guide__img"><img src="'.$page->getValue('image').'" />
						<div class="guide__name">'.$page->getValue('name').'</div>
					</div>
					<div class="guide__content c2">
						<a href="" class="guide__title">'.$page->getValue('post').'</a><br>
						<div class="guide__text">
						'.$page->getValue('academic_degree').'
						</div>
						<div class="guide__contacts">';
						if ($page->getValue('phone')) {
							echo '<div class="guide__phone"><a href="tel:'.$page->getValue('phone').'">'.$page->getValue('phone').'</a></div>
							';
						}
						if ($page->getValue('address')) {
							echo '<div class="guide__address">'.$page->getValue('address').'</div>
							';
						}
						if ($page->getValue('email')) {
							echo '<div class="guide__email"><a href="mailto:'.$page->getValue('email').'">'.$page->getValue('email').'</a></div>
							';
						}
						if ($page->getValue('blog')) {
							echo '<div class="guide__link"><a href="/rectors-blog/" target="_blank">'.$page->getValue('blog').'</a></div>
							';
						}
			echo '</div>
					</div>
				</div>
			</div>';
			}
				break;
			
			default:
				if ($variables['@pageId'] == 6) {
				echo	$this->render($this->macros('content', 'menu', array(null, 3, $variables['@pageId'])), 'macros/guide');
			}	else {
					$hierarchy = umiHierarchy::getInstance();
					$page = $hierarchy->getElement($variables['@pageId']);
				echo '
			<div class="row">
				<div class="guide">
					<div class="guide__img"><img src="'.$page->getValue('image').'" />
						<div class="guide__name">'.$page->getValue('name').'</div>
					</div>
					<div class="guide__content c3">
						<a href="" class="guide__title">'.$page->getValue('post').'</a><br>
						<div class="guide__text">
						'.$page->getValue('academic_degree').'
						</div>
						<div class="guide__contacts">';
						if ($page->getValue('phone')) {
							echo '<div class="guide__phone"><a href="tel:'.$page->getValue('phone').'">'.$page->getValue('phone').'</a></div>
							';
						}
						if ($page->getValue('address')) {
							echo '<div class="guide__address">'.$page->getValue('address').'</div>
							';
						}
						if ($page->getValue('email')) {
							echo '<div class="guide__email"><a href="mailto:'.$page->getValue('email').'">'.$page->getValue('email').'</a></div>
							';
						}
						if ($page->getValue('blog')) {
							echo '<div class="guide__link"><a href="/rectors-blog/" target="_blank">'.$page->getValue('blog').'</a></div>
							';
						}
						echo '</div>
						<div class="guide__text">
						'.$page->getValue('content').'
						</div>
					</div>
				</div>
			</div>';
			}
				break;
		}
		?>
	</div>
</div>
<!---------------- Футер ---------------->
<? include 'footer.phtml'; ?>