<?
/*print_r('<pre>');
print_r($variables['void:lines']);
print_r('</pre>');*/
$hierarchy = umiHierarchy::getInstance();
//print_r($hierarchy);




foreach ($variables['items']['nodes:item'] as $news) {
  
  
  $page = $hierarchy->getElement($news['@id']);

  echo '
  
    <div class="col-lg-4 col-md-6 col-sm-6">
      <div class="graduate__item">
        <div class="graduate__cover"></div>
        <div class="graduate__img"><img src='. $page->getValue('header_pic').' /> </div>
        <div class="graduate__title">'.$news['@name'] .'  </div>
      </div>
    </div>
    ';

}


?>