<?php
echo '<ul class="nav">';
echo '<li><a class="nav__logo" href="/'.urlencode($_REQUEST['lang']).'"><img src="/templates/ksu/img/logo-black.svg" alt="ksu"></a></li>';
foreach ($variables['items']['nodes:item'] as $item) :
	echo '<li class="nav__item">';
	if(!($item['items'])) echo'<a href="'.$item['@link'].'">';
	echo $link = in_array($item['@id'], [59, 545]) ? '<a href="'.$item['@link'].'">'.$item['@name'].'</a>' : $item['@name'];
	if ($item['items']) :
		echo '<ul class="nav__item-dropdown">';
		foreach ($item['items']['nodes:item'] as $underitem) :
			$target = in_array($underitem['@id'], [45, 83, 109, 4305, 4306, 4307, 4510, 5853]) ? '_blank' : '_self';

			echo '<li><a href="'.$underitem['@link'].'" target="'.$target.'">'.$underitem['@name'].'</a></li>';

		endforeach;
		echo '</ul>';
	endif;
	if(!($item['items'])) echo'</a>';
	echo '</li>';
endforeach;
echo '</ul>';
?>