<? include "./templates/ksu/php/partials/header.phtml"; ?>

<div class="container">
	<div class="tape">
		<h1 class="tape__title" style="text-align: center;">
			<?= $variables['@header'] ?>
		</h1>
		<div class="tape__wrapper">
			<?
				$announcements = $this->macros('news', 'lastlist', ['announcements', 'null', 5]);
				$hierarchy = umiHierarchy::getInstance();
				if ($announcements) :
					foreach ($announcements["void:lines"] as $announcement) :
						$data = $hierarchy->getElement($announcement['attribute:id']);
						echo '
						<a class="tape__item" href="'.$announcement['attribute:link'].'" style="width: 100%;">
							<div class="tape__date">'.$data->getValue('publish_time')->getFormattedDate('d').'&nbsp;'.$this->translate($data->getValue('publish_time')->getFormattedDate('m')).'<br>'.$data->getValue('publish_time')->getFormattedDate('Y').'</div>
							<div class="tape__anons">'.$announcement['node:name'].'</div>
						</a>';
					endforeach;
				else :
					echo $this->translate('no_ad').'!';
				endif;
				
				$limit = 3; //ссылок в навигации на каждую сторону
				$per_page = $announcements['per_page']; // элементов на странице
				$total = $announcements['total'];
				echo $this->render(array(
					"total" => $total,
					"per_page" => $per_page,
					"limit" => $limit,
					"numpages" => $this->macros("system", "numpages", array($total, $per_page, null, null, $limit))
				), "partials/pagination/pagination");
			?>
		</div>
	</div>
	<div class="page">
		<div class="page__content-box">
			<div class="page__content">
				<?
				$hierarchy = umiHierarchy::getInstance();
				$page = $hierarchy->getElement($variables['@pageId']);
				echo $page->content;
				?>
			</div>
		</div>
	</div>
</div>

<? include "./templates/ksu/php/partials/footer.phtml"; ?>