<? include "./templates/ksu/php/partials/header.phtml"; ?>
<!-- Эти стили добавить к себе в gulp -->
<link rel="stylesheet" href="/templates/ksu/css/blog.css">

<section id="news-item">
	<div class="container">
		<div class="page-content">
			<?
			$hierarchy = umiHierarchy::getInstance();
			$page = $hierarchy->getElement($variables['@pageId']);
			?>
			<h1 class="title-content"><? print_r($page->getValue('h1')); ?></h1>

			<div class="blog_text">
				<div class="img_wrapper">
					<img class="img" src="/templates/ksu/img/attach/alma-doshhanova.jpg" />
					<div class="rector_name">
						<p><strong>Дощанова Алма Иргибаевна</strong></p>
						<p><?= $this->translate("blog_line1"); ?></p>
						<p><?= $this->translate("blog_line2"); ?></p>
					</div>
				</div>
				<div class="text_wrapper">
					<?= $page->getValue('info') ?>
				</div>
			</div>
			<div class="content_news">
				<?= $this->render($this->macros('blogs20', 'commentAdd', array('1965', 'default')), 'partials/blogs/comment-add'); ?>
			</div>
			<div class="content_news">
				<?= $this->render($this->macros('comments', 'insert', array('1965', 'default')), 'partials/blogs/comment-list'); ?>
			</div>
		</div>
	</div>
</section>
<script src="https://www.google.com/recaptcha/api.js"></script>
<script>
	function onSubmit(token) {
		document.getElementById("form_for_comments").submit();
	}
</script>
<? include 'footer.phtml'; ?>
<script src="/templates/ksu/js/readmore.js"></script>
<script>
	$(document).ready(function() {
		if ($(window).width() <= 767) {
			$('.text_wrapper').addClass('rm');
		} else {
			$('.text_wrapper').removeClass('rm');
		}
		$(window).resize(function() {
			if ($(window).width() <= 767) {
				$('.text_wrapper').addClass('rm');
			} else {
				$('.text_wrapper').removeClass('rm');
			}

			//$('.text_wrapper.rm').readmore();
		});
		//$('.text_wrapper.rm').readmore();
	});
</script>

<? include "./templates/ksu/php/partials/footer.phtml"; ?>