<? include "./templates/ksu/php/partials/header.phtml"; ?>
<?php
	$hierarchy = umiHierarchy::getInstance();
	$getParentPage = $hierarchy->getParent($variables['@pageId']);
	$parentPage = $hierarchy->getElement($getParentPage);
	$getChildrenPageList = $hierarchy->getChildrenTree($variables['@pageId']);

	$page = $hierarchy->getElement($variables['@pageId']);
	$currentPage = $hierarchy->getElement($variables['@pageId']);
	$rootPageId = $currentPage->id;

	do {
		$rootPage = $hierarchy->getElement($rootPageId);
	} while ($rootPageId = $hierarchy->getParent($rootPageId));
    
    
    
    function getDirContent($path) {
        $content = scandir($path);

        $dirs = [];
        $files = [];

        foreach ($content as $item) {
          if ($item === '.' || $item === '..') {
            continue;
          }

          $title = explode('.', $item);
          if (count($title) > 0) {
            unset($title[count($title) - 1]);
          }
          
          $title = implode('.', $title);

          if (is_dir($path.'/'.$item)) {
            $dirs[] = [
              'id' => uniqid(rand(), false),
              'title' => $item,
              'path' => $item,
              'children' => getDirContent($path.'/'.$item),
            ];
          } else {
            $files[] = [
              'id' => uniqid(rand(), false),
              'title' => $title,
              'path' => $item,
            ];
          }
        }

        return array_merge($dirs, $files);
    }
    
  function mb_strcasecmp($str1, $str2, $encoding = null) {
    if (null === $encoding) {
    	$encoding = mb_internal_encoding();
    }
    return strcmp(mb_strtolower($str1, $encoding), mb_strtolower($str2, $encoding));
  }

  function sortItems($a, $b) {
    if (array_key_exists('children', $a) && array_key_exists('children', $b)) {
      return mb_strcasecmp($a['title'], $b['title']);
    }

    if (array_key_exists('children', $a)) {
      return 1;
    }
    if (array_key_exists('children', $b)) {
      return -1;
    }

    return mb_strcasecmp($a['title'], $b['title']);
  }

  function printData($data, $path) {
    $list_started = false;
    foreach ($data as $item) {
      if (array_key_exists('children', $item)) {
        if (count($item['children']) > 0) {
          printDir($item, $path);
        }
      } else {
        if (!$list_started) {
          $list_started = true;
          echo '<ul class="mb-0">';
        }
        printItem($item, $path);
      }
    }

    if ($list_started) {
      echo '</ul>';
    }
  }

  function printItem ($item, $path) {
      echo '<li><a href="https://ksu.edu.kz/curriculum/'.$path.$item['path'].'" target="_blank">'.$item['title'].'</a></li>';
  }
  function printDir($dir, $path) {
    ?>
    <div class="card mb-3">
      <div class="card-header">
        <h2 class="mb-0">
          <button class="btn btn-link btn-block text-left" type="button" data-toggle="collapse" data-target="#dir-<?php echo $dir['id'] ?>" aria-controls="collapseOne">
            <?php if ($path === '/') { echo '<b>'; } ?>
            <?php echo $dir['title']; ?>
            <?php if ($path === '/') { echo '</b>'; }?>
          </button>
        </h2>
      </div>
      <div id="dir-<?php echo $dir['id'] ?>" class="collapse" aria-labelledby="headingOne">
        <div class="card-body">
          <?php printData($dir['children'], $path.$dir['path'].'/'); ?>
        </div>
    </div>
    </div>
    <?php
  }
?>

<div class="container">
	<div class="page">
		<div class="page__content-box">
			<h1 class="page__content-title">
				<?= $variables['@header'] ?>
			</h1>
			<div class="page__content">
				<?
					if ($page->header_pic) :
						echo '<div class="page__content-images" style="background: url('.$page->header_pic.') no-repeat center / cover"></div>';
					endif;
                    
                    $lang = $variables['@lang'] ?: 'ru';
                    $rootDir = getServer('DOCUMENT_ROOT').'/curriculum/'.$lang;
                    
                    $data = getDirContent($rootDir);
                    
					echo $page->content;
                    
                    printData($data, '/'.$lang.'/');
				?>
<!--                
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
-->
<link rel="stylesheet" href="/curriculum/style.css">

<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
			</div>
		</div>
		<div class="page__sidebar-box">
			<? if ($page->page_sidebar_visible !== 1) : ?>
			<div class="page__sidebar-item">
				<div class="page__sidebar-title">
					<?= $rootPage->name ?>
				</div>
				<div class="page__sidebar-list">
					<?
						if ($parentPage->menu_sidebar_show) {
							echo '<a href="' . $parentPage->link . '" class="page__sidebar-link"><b>' . $parentPage->getValue('menu_sidebar_title') . '</b></a>';
						}
						if (empty($getChildrenPageList)) :
							echo $this->render($this->macros('content', 'menu', array(null, 1, $getParentPage)), 'partials/sidebar/sidebar-item');
						else :
							echo $this->render($this->macros('content', 'menu', array(null, 1, $variables['@pageId'])), 'partials/sidebar/sidebar-item');
						endif;
					?>
				</div>
			</div>
			<? endif ?>

			<? if ($page->page_sidebar_links || $page->spisok || $page->vlozhenie) : ?>
			<div class="page__sidebar-item page__sidebar-item--not-title">
				<div class="page__sidebar-list page__sidebar-list--links">
					<?= $page->page_sidebar_links ?>
					<?= $page->spisok ?>
					<?= $page->vlozhenie ?>
				</div>
			</div>
			<? endif ?>
		</div>
	</div>
</div>

<? include "./templates/ksu/php/partials/footer.phtml"; ?>