<? include "./templates/ksu/php/partials/header.phtml"; ?>

<div class="container-с">
	<?php
	$fullP = $variables['full:page']->getAltName();

	// Рус
	if ($variables['@pageId'] == '2') {
		$fullP = $variables['@pageId'];
	}
	if ($variables['@pageId'] == '1942') {
		$fullP = $variables['@pageId'];
	}
	if ($variables['@pageId'] == '1931') {
		$fullP = $variables['@pageId'];
	}
	if ($variables['@pageId'] == '1932') {
		$fullP = $variables['@pageId'];
	}
	if ($variables['@pageId'] == '1933') {
		$fullP = $variables['@pageId'];
	}
	if ($variables['@pageId'] == '1934') {
		$fullP = $variables['@pageId'];
	}
	if ($variables['@pageId'] == '1929') {
		$fullP = $variables['@pageId'];
	}
	if ($variables['@pageId'] == '3762') {
		$fullP = $variables['@pageId'];
	}
	if ($variables['@pageId'] == '1936') {
		$fullP = $variables['@pageId'];
	}
	if ($variables['@pageId'] == '4376') {
		$fullP = $variables['@pageId'];
	}

	// Каз
	if ($variables['@pageId'] == '117') {
		$fullP = $variables['@pageId'];
	}
	if ($variables['@pageId'] == '1944') {
		$fullP = $variables['@pageId'];
	}
	if ($variables['@pageId'] == '1945') {
		$fullP = $variables['@pageId'];
	}
	if ($variables['@pageId'] == '1946') {
		$fullP = $variables['@pageId'];
	}
	if ($variables['@pageId'] == '1947') {
		$fullP = $variables['@pageId'];
	}
	if ($variables['@pageId'] == '1948') {
		$fullP = $variables['@pageId'];
	}
	if ($variables['@pageId'] == '3763') {
		$fullP = $variables['@pageId'];
	}
	if ($variables['@pageId'] == '4380') {
		$fullP = $variables['@pageId'];
	}

	// Анг
	if ($variables['@pageId'] == '1949') {
		$fullP = $variables['@pageId'];
	}
	if ($variables['@pageId'] == '1951') {
		$fullP = $variables['@pageId'];
	}
	if ($variables['@pageId'] == '1952') {
		$fullP = $variables['@pageId'];
	}
	if ($variables['@pageId'] == '1953') {
		$fullP = $variables['@pageId'];
	}
	if ($variables['@pageId'] == '1954') {
		$fullP = $variables['@pageId'];
	}
	if ($variables['@pageId'] == '1955') {
		$fullP = $variables['@pageId'];
	}
	if ($variables['@pageId'] == '3764') {
		$fullP = $variables['@pageId'];
	}
	if ($variables['@pageId'] == '64') {
		$fullP = $variables['@pageId'];
	}
	?>

	<? if ($variables['@pageId'] == $fullP) { ?>
	<div class="page-news">
		<div class="page-news__list">
			<?php
			switch ($variables['@pageId']) {
				case '1936':
					echo $this->render($this->macros('news', 'lastlist', array('newslist/all-news, newslist/for-the-entrant, newslist/education, newslist/science, newslist/university-life, newslist/ruhani-zhagyru, newslist/stop-corruption', null, 15)), 'partials/news/news-item');
					break;
				case '117':
					echo $this->render($this->macros('news', 'lastlist', array('newslist/all-news, newslist/for-the-entrant, newslist/education, newslist/science, newslist/university-life, newslist/ruhani-zhagyru, newslist/stop-corruption', null, 15)), 'partials/news/news-item');
					break;
				case '64':
					echo $this->render($this->macros('news', 'lastlist', array('newslist/all-news, newslist/for-the-entrant, newslist/education, newslist/science, newslist/university-life, newslist/ruhani-zhagyru, newslist/stop-corruption', null, 15)), 'partials/news/news-item');
					break;
				case '2':
					echo $this->render($this->macros('news', 'lastlist', array('newslist/all-news, newslist/for-the-entrant, newslist/education, newslist/science, newslist/university-life, newslist/ruhani-zhagyru, newslist/stop-corruption', null, 15)), 'partials/news/news-item');
					break;
				case '1942':
					echo $this->render($this->macros('news', 'lastlist', array('newslist/all-news, newslist/for-the-entrant, newslist/education, newslist/science, newslist/university-life, newslist/ruhani-zhagyru, newslist/stop-corruption', null, 15)), 'partials/news/news-item');
					break;
				case '1949':
					echo $this->render($this->macros('news', 'lastlist', array('newslist/all-news, newslist/for-the-entrant, newslist/education, newslist/science, newslist/university-life, newslist/ruhani-zhagyru, newslist/stop-corruption', null, 15)), 'partials/news/news-item');
					break;

				default:
					echo $this->render($this->macros('news', 'lastlist', array($variables['@pageId'], null, 15)), 'partials/news/news-item');
					break;
			}
			?>
		</div>
		<div class="page-news__right">
			<div class="page-news-category">
				<div class="page-news-title">
					<?= $this->translate("rubrics"); ?>
				</div>
				<div class="page-news-box">
					<?
						$lastlist = $this->macros("news", "lastlents", ["/newslist",0,10,1]);
						foreach ($lastlist["void:lines"] as $newslist) :

							$lang = 'ru';
							$link = $newslist["attribute:link"];
							if ($lang == 'ru' and (strpos($link, '/ru') !== 0) and (strpos($_SERVER['REQUEST_URI'], '/ru') === 0)) {
								$link = '/ru'.$link;
							}
							$isActive = ($link == $_SERVER['REQUEST_URI']) ? 'current' : '';

							echo '
								<a href="'.$newslist["attribute:link"].'" class="page-news-category__item '.$isActive.'">
									'.$this->translate($this->getPageById($newslist["attribute:id"])->getAltName()).'
								</a>
							';
						endforeach;
					?>
				</div>
			</div>
			<?
				$hierarchy = umiHierarchy::getInstance();
				$getId = $this->macros('content', 'get_page_id', array('/home/'));
				$value = $hierarchy->getElement($getId);
				if ($value) :
			?>
			<? 
			$events = $this->macros('news', 'lastlist', ['conferences', 0, 2, 1]);
			if ($events) : ?>
			<div class="page-news-category">
				<div class="page-news-title">
					<?= $this->translate('conferences'); ?>
				</div>
				<div class="page-news-events">
					<div class="page-news-events__lists">
						<? $i = 0;
						foreach ($events["items"]["nodes:item"] as $event) :
							$page = $hierarchy->getElement($event['attribute:id']);
							echo '
								<a href="'.$event["attribute:link"].'" class="page-news-events__item" style="display:block;">
									'.$event["node:name"].'
									<span>'.$this->translate(strtolower($page->getValue('date_of_the_event')->getFormattedDate('l'))).', '.$page->getValue('date_of_the_event')->getFormattedDate('d').' '.$this->translate(strtolower($page->getValue('date_of_the_event')->getFormattedDate('F'))).'</span>
								</a>
							';
							$i++; if($i>=2) break;
						endforeach ?>
					</div>
				</div>
				<a href="/<?= $variables['@lang'] ?>/conferences" class="page-news-events__button"><?= $this->translate('all_conferences'); ?></a>
			</div>
			<? endif ?>
			<div class="page-news-category page-news-category--mobile">
				<div class="page-news-title">
					<?= $this->translate("page_contacts"); ?>
				</div>
				<div class="page-news-contacts">
					<?= $value->getValue('content') ?>
				</div>
			</div>
			<? endif; ?>
		</div>
	</div>
	<div class="page-news-category page-news-category--mobile-bottom" style="display: none;">
		<div class="page-news-title">
			<?= $this->translate("page_contacts"); ?>
		</div>
		<div class="page-news-contacts">
			<?= $value->getValue('content') ?>
		</div>
	</div>
	<? } else { ?>
	<?
		$hierarchy = umiHierarchy::getInstance();
		$page = $hierarchy->getElement($variables['@pageId']);
		$content = $page->getValue('anons');
		$words_per_minute = "150"; // Время чтения слов в минуту
		$img_per_minute = "0"; // Время чтения изображения в секундах
		$img_numb = preg_match_all("~<img~i", $content, $result_numb); // Плучаем общее количество изображений в тексте
		$text_read = round(count(preg_split("/[\s,]+/", $content)) / $words_per_minute, 1); // Получаем общее время чтения текста

		$img_read = floor((count($result_numb[0]) * $img_per_minute) / 60); // Получаем общее время чтения изображений
		$all_read = $img_read + $text_read; // Получаем общее время чтения (текст + изображения)
		function decl_of_numb($all_numb, $titles)	{
			$cases = array(2, 0, 1, 1, 1, 2);
			return $all_numb . " " . $titles[($all_numb % 100 > 4 && $all_numb % 100 < 20) ? 2 : $cases[min($all_numb % 10, 5)]];
		}
	?>

	<h1 class="news-entry-title"><?= $variables['@header']; ?></h1>
	<div class="news-entry-info">
		<div class="news-entry-info__text news-entry-info__text">
			<? if ($variables["parents"]['+page'][0]->getAltName() !== 'conferences') : echo $this->translate('published'); else : echo $this->translate('published'); endif; ?>:
			<span>
				<? echo $this->translate(strtolower($page->publish_time->getFormattedDate('j'))); echo ' '; echo $this->translate(strtolower($page->publish_time->getFormattedDate('F'))); echo ' '; echo $this->translate(strtolower($page->publish_time->getFormattedDate('Y'))); ?>
			</span>
		</div>
		<div class="news-entry-info__text news-entry-info__text--read">
			<?= $this->translate('read') ?> <? echo decl_of_numb(round($all_read), array("мин", "мин", "мин")); ?>
		</div>
		<div class="news-entry-info__text news-entry-info__text--views">
			<?= $this->macros('custom', 'counter', [$variables['@pageId']]); ?>
		</div>
	</div>
	<div class="news-entry-container">
		<?
			if ($page->header_pic) :
				echo '<div class="page__content-images" style="background: url('.$page->header_pic.') no-repeat center / cover"></div>';
			endif;
		?>
		<?
			$hierarchy = umiHierarchy::getInstance();
			$page = $hierarchy->getElement($variables['@pageId']);
			echo $page->getValue('anons');
		?>
		<div class="ya-share2" data-services="vkontakte,facebook,whatsapp,telegram,twitter,odnoklassniki" data-shape="round" data-size="m"></div>
	</div>
	<? } ?>
</div>

<? include "./templates/ksu/php/partials/footer.phtml"; ?>