<? include "./templates/ksu/php/partials/header.phtml"; ?>

<div class="container">
	<div class="page-content">
		<h1 class="page__content-title">
			<?= $variables['@header'] ?>
		</h1>
		<?
		$hierarchy = umiHierarchy::getInstance();
		$page = $hierarchy->getElement($variables['@pageId']) ?: $hierarchy->getElement($current_page_id);
		print_r($page ? $page->getValue('content') : '');
		?>
		<? if ($page && $page->getValue('pic_list')) { ?>
			<div class="images">
				<?
				foreach ($page->getValue('pic_list') as $newspic) {
					$data = $this->macros('system', 'makeThumbnail', array($newspic->getFilePath(), auto, 00));
					print_r('<a class="mfp_img" href="' . $data['src'] . '"><img src="' . $data['src'] . '" alt="Alt"></a>');
				}
				?>
			<? }
			?>
			</div>
	</div>
</div>

<? include "./templates/ksu/php/footer.phtml"; ?>