<? include "./templates/ksu/php/partials/header.phtml"; ?>
<?php
	$hierarchy = umiHierarchy::getInstance();
	$getParentPage = $hierarchy->getParent($variables['@pageId']);
	$parentPage = $hierarchy->getElement($getParentPage);
	$getChildrenPageList = $hierarchy->getChildrenTree($variables['@pageId']);

	$page = $hierarchy->getElement($variables['@pageId']);
	$currentPage = $hierarchy->getElement($variables['@pageId']);
	$rootPageId = $currentPage->id;

	do {
		$rootPage = $hierarchy->getElement($rootPageId);
	} while ($rootPageId = $hierarchy->getParent($rootPageId));
?>

<div class="container">
	<div class="page">
		<div class="page__content-box">
			<h1 class="page__content-title">
				<?= $variables['@header'] ?>
			</h1>
			<div class="page__content">
				<?
					if ($page->header_pic) :
						echo '<div class="page__content-images" style="background: url('.$page->header_pic.') no-repeat center / cover"></div>';
					endif;
					
					if (empty(!$page->slider_images)) : ?>
					<div class="swiper-about">
						<div class="swiper-wrapper">
							<?
								foreach ($page->slider_images as $key => $value) :
									echo '
										<div class="swiper-slide">
											<div class="swiper-about__image swiper-lazy" data-background="'.$value.'" style="background-image: url('.$value.')"></div>
										</div>
									';
								endforeach;
							?>
						</div>
						<div class="swiper-pagination"></div>
						<div class="swiper-navigation">
							<div class="swiper-button-prev"></div>
							<div class="swiper-button-next"></div>
						</div>
					</div>
					<? endif;

					$getPageById = $this->getPageById($variables['@pageId']);
					$children = $hierarchy->getChildrenTree($variables['@pageId']);
					if (!$getPageById->getValue('content') && count($children) > 0) {
						reset($children);
						$this->macros('content', 'redirect', array($this->getPageById(key($children))->link));
					}
					echo $page->content;
				?>
			</div>
		</div>
		<div class="page__sidebar-box">
			<? if ($page->page_sidebar_visible !== 1) : ?>
			<div class="page__sidebar-item">
				<div class="page__sidebar-title">
					<?= $rootPage->name ?>
				</div>
				<div class="page__sidebar-list">
					<?
						if ($parentPage->menu_sidebar_show) {
							echo '<a href="' . $parentPage->link . '" class="page__sidebar-link"><b>' . $parentPage->getValue('menu_sidebar_title') . '</b></a>';
						}
						if (empty($getChildrenPageList)) :
							echo $this->render($this->macros('content', 'menu', array(null, 1, $getParentPage)), 'partials/sidebar/sidebar-item');
						else :
							echo $this->render($this->macros('content', 'menu', array(null, 1, $variables['@pageId'])), 'partials/sidebar/sidebar-item');
						endif;
					?>
				</div>
			</div>
			<? endif ?>

			<? if ($page->page_sidebar_links || $page->spisok || $page->vlozhenie) : ?>
			<div class="page__sidebar-item page__sidebar-item--not-title">
				<div class="page__sidebar-list page__sidebar-list--links">
					<?= $page->page_sidebar_links ?>
					<?= $page->spisok ?>
					<?= $page->vlozhenie ?>
				</div>
			</div>
			<? endif ?>
		</div>
	</div>
</div>

<? include "./templates/ksu/php/footer.phtml"; ?>