<div class="search-wrapper"></div>
<div class="search">
	<div class="search__box">
		<form class="search-form" action="/<?= $variables['@lang'] ?>/result" method="GET">
			<input class="search-form__input" name="search" id="search" type="text" placeholder="<?= $this->translate("enter_text") ?>"></input>
			<input class="search-form__btn" type="submit" value="<?= $this->translate("search") ?>">
		</form>
	</div>
</div>

<footer class="footer">
	<img src="/templates/ksu/img/footer-ksu.png" alt="KSU" class="footer__img">
	<div class="footer__text"><?= $this->translate('footer_copyright'); ?></div>
</footer>

<!-- <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script> -->
<script src="/templates/ksu/js/institute/app.min.js?<? echo $js_version ?>"></script>
<script src="https://yastatic.net/share2/share.js" defer></script>
</body>

</html>