<? 
	include "header.phtml"; 
	$getPageById = $this->getPageById($variables['@pageId']);
	$hierarchy = umiHierarchy::getInstance();
	$current_page_id = cmsController::getInstance()->getCurrentElementId();
	$page = $hierarchy->getElement($variables['@pageId']) ?: $hierarchy->getElement($current_page_id);
?>

<div class="container">
	<div class="breadcrumbs">
		<a href="/<?= $variables['@lang'] ?>/"><?= $variables['@title'] ?></a>
		<?= $this->render($this->macros('core', 'navibar'), 'institute/breadcrumbs') ?>
	</div>



	<div class="page">
		<div class="content">
			<div class="content-header">
				<?= $variables['@header'] ?>
			</div>
			<div class="content-body">
				<? if (empty(!$page->image)) : ?>
					<div class="swiper-about">
						<div class="swiper-wrapper">
							<?
								foreach ($page->image as $key => $value) :
									echo '
										<div class="swiper-slide">
											<div class="swiper-about__image swiper-lazy" data-background="'.$value.'" style="background-image: url('.$value.')"></div>
										</div>
									';
								endforeach;
							?>
						</div>
						<div class="swiper-pagination"></div>
						<div class="swiper-navigation">
							<div class="swiper-button-prev"></div>
							<div class="swiper-button-next"></div>
						</div>
					</div>
				<? endif ?>
				<?php
					echo $getPageById ? $getPageById->getValue('content') : ($page ? $page->getValue('content') : $this->render($variables, $variables['@module'] .'/'.$variables['@method']));
				?>
			</div>
		</div>
	</div>



</div>

<? include 'footer.phtml'; ?>