<?
switch ($variables['@lang-id']) :
		case '1':
			$lang = 'ru';
			break;
		case '2':
			$lang = 'kz';
			break;
		case '3':
			$lang = 'en';
			break;
		default:
			$lang = 'ru';
			break;
	endswitch;

foreach ($variables['items']['nodes:item'] as $value) {
	$link = $value['@link'];
	if ($lang == 'ru' and (strpos($link, '/ru') !== 0) and (strpos($_SERVER['REQUEST_URI'], '/ru') === 0)) {
		$link = '/ru'.$link;
	}
	$isActive = ($link == $_SERVER['REQUEST_URI']) ? 'current' : '';
	
	echo '<a href="'.$value['@link'].'" class="'.$isActive.'">'.$value['@name'].'</a>';
}

?>