<? include "header.phtml"; ?>

<div class="container">
	<div class="breadcrumbs">
		<a href="/"><?= $variables['@title'] ?></a>
		<?= $this->render($this->macros('core', 'navibar'), 'institute/breadcrumbs') ?>
	</div>
	<div class="sidebar">
		<div class="sidebar__content">
			<div class="team__box">
				<? $value = $hierarchy->getElement($variables['@pageId']); ?>
				<div class="team__box-inner">
					<div class="team__img" style="background: url(<?= $value->getValue('photo_pps'); ?>) center center / cover no-repeat; width: 195px; height: 230px"></div>
					<div class="team__full-information">
						<? if ($value->getValue('h1')) : ?>
						<div class="team__name">
							<?= $value->getValue('h1') ?>
						</div>
						<? endif; if ($value->getValue('place_pps')) : ?>
						<div class="team__place">
							<?= $value->getValue('place_pps'); ?>
							<span><?= $this->translate('team_place') ?></span>
						</div>
						<? endif; if ($value->getValue('degree_pps')) : ?>
						<div class="team__place">
							<?= $value->getValue('degree_pps'); ?>
							<span><?= $this->translate('team_degree') ?></span>
						</div>
						<? endif; if ($value->getValue('academic_degree_pps')) : ?>
						<div class="team__place">
							<?= $value->getValue('academic_degree_pps'); ?>
							<span><?= $this->translate('team_academic_degree') ?></span>
						</div>
						<? endif; if ($value->getValue('email_pps')) : ?>
						<div class="team__place">
							<?= $value->getValue('email_pps'); ?>
							<span><?= $this->translate('team_email') ?></span>
						</div>
						<? endif; if ($value->getValue('phone_pps')) : ?>
						<div class="team__place">
							<?= $value->getValue('phone_pps'); ?>
							<span><?= $this->translate('team_phone') ?></span>
						</div>
						<? endif; ?>
					</div>
				</div>
				<div class="team__content">
					<?= $value->getValue('content'); ?>
				</div>
			</div>
		</div>	
		<div class="sidebar__nav">
			<? 
				$getChildrenList = $hierarchy->getChildrenTree($variables['@pageId']);
				if (empty($getChildrenList)) {
					$getParentList = $hierarchy->getParent($variables['@pageId']);
					echo $this->render($this->macros('content', 'menu', array(null, 4, $getParentList)), 'institute/sidebar_item');
				} else {
					foreach ($getChildrenList as $key => $value) {
						$element = $hierarchy->getElement($key);
						echo '<a href="'.$element->getAltName().'">'.$element->getName().'</a>';
					}
				}
			?>
		</div>
	</div>
</div>

<? include 'footer.phtml'; ?>